Repository neojelll/DocuTide, pull requests merged in 2025-02, with the labels that each got.

#14 refactor: architecture update
  .github/workflows/update-diagrams.yml
  architecture/.vscode/settings.json
  architecture/architecture/containers-diagram.py
  architecture/architecture/docs-editor-relationships-diagram.py
  architecture/architecture/messagebroker-relationships-diagram.py
  architecture/architecture/mvp-diagram.py
  architecture/diagrams/containers-diagram.png
  architecture/diagrams/docs-editor-relationships-diagram.png
  architecture/diagrams/messagebroker-relationships-diagram.png
  architecture/diagrams/mvp-diagram.png
Labels: enhancement

#17 fix: file path in docker-compose
  docker/docker-compose.yml
Labels: wontfix

#16 fix(api-gateway): send to kafka methods
  apps/api-gateway/src/auth/auth.controller.ts
  apps/api-gateway/src/auth/auth.module.ts
  apps/api-gateway/src/auth/auth.service.ts
  apps/api-gateway/src/projects/projects.controller.ts
  apps/api-gateway/src/projects/projects.module.ts
  apps/api-gateway/src/projects/projects.service.ts
  apps/api-gateway/src/users/users.controller.ts
  apps/api-gateway/src/users/users.module.ts
  apps/api-gateway/src/users/users.service.ts
Labels: wontfix

#20 feat(api-gateway): add auth for jwt
  .env.example
  apps/api-gateway/src/api-gateway.module.ts
  apps/api-gateway/src/auth/auth.controller.ts
  apps/api-gateway/src/auth/auth.module.ts
  apps/api-gateway/src/auth/auth.service.ts
  apps/api-gateway/src/auth/guards/jwt-auth.guard.ts
  apps/api-gateway/src/auth/interfaces/jwt.interface.ts
  apps/api-gateway/src/auth/strategy/jwt.strategy.ts
  apps/api-gateway/src/projects/projects.controller.ts
  apps/api-gateway/src/projects/projects.module.ts
  apps/api-gateway/src/projects/projects.service.ts
  apps/api-gateway/src/users/users.controller.ts
  apps/api-gateway/src/users/users.module.ts
  apps/api-gateway/src/users/users.service.ts
  package-lock.json
  package.json
Labels: enhancement

#15 refactor(docs): description
  README.md
Labels: documentation

#25 fix: set secret in create accessToken method
  apps/api-gateway/src/auth/auth.service.ts
Labels: bug

#26 feat: add DocsDto
  libs/docs/src/docs.module.ts
  libs/docs/src/dto/docs.dto.ts
  libs/docs/src/dto/index.ts
  libs/docs/src/index.ts
  libs/docs/tsconfig.lib.json
  nest-cli.json
  package.json
  tsconfig.json
Labels: enhancement

#29 feat(api-gateway): add routes for docs-editor microservice
  apps/api-gateway/src/docs-editor/docs-editor.controller.ts
  apps/api-gateway/src/docs-editor/docs-editor.module.ts
  apps/api-gateway/src/docs-editor/docs-editor.service.ts
Labels: enhancement

#36 fix: add .env files in gitignore
  .gitignore
Labels: fix

#35 refactor: add constructor in all DTO
  libs/docs/src/lib/dto/docs.dto.ts
  libs/project/src/lib/dto/project-create.dto.ts
  libs/project/src/lib/dto/project-read.dto.ts
  libs/project/src/lib/dto/project-update.dto.ts
  libs/user/src/lib/dto/user-read.dto.ts
  libs/user/src/lib/dto/user-sign-in.dto.ts
  libs/user/src/lib/dto/user-sign-up.dto.ts
  libs/user/src/lib/dto/user-update.dto.ts
Labels: refactor

#39 fix: mongoose-dependencies
  package.json
  pnpm-lock.yaml
Labels: fix

#40 refactor: add strictPropertyInitialization settings in compiler options
  tsconfig.base.json
Labels: refactor

#38 refactor: routes and add DTO annotation
  apps/api-gateway/src/app/auth/auth.controller.ts
  apps/api-gateway/src/app/auth/decorators/jwt-decode.decorator.ts
  apps/api-gateway/src/app/docs-editor/docs-editor.controller.ts
  apps/api-gateway/src/app/docs-editor/docs-editor.service.ts
  apps/api-gateway/src/app/projects/projects.controller.ts
  apps/api-gateway/src/app/projects/projects.service.ts
  apps/api-gateway/src/app/users/users.controller.ts
  apps/api-gateway/src/app/users/users.service.ts
Labels: refactor

#43 refactor: libs structure
  apps/api-gateway/src/app/auth/auth.module.ts
  apps/api-gateway/src/app/auth/auth.service.ts
  apps/api-gateway/src/app/docs-editor/docs-editor.controller.ts
  apps/api-gateway/src/app/docs-editor/docs-editor.service.ts
  apps/api-gateway/src/app/projects/projects.controller.ts
  apps/api-gateway/src/app/projects/projects.service.ts
  apps/api-gateway/src/app/users/users.controller.ts
  apps/api-gateway/src/app/users/users.service.ts
  libs/core/auth/README.md
  libs/core/auth/jest.config.ts
  libs/core/auth/project.json
  libs/core/auth/src/index.ts
  libs/core/auth/src/lib/auth.module.ts
  libs/core/auth/src/lib/decorators/jwt-decode.decorator.ts
  libs/core/auth/src/lib/guards/jwt-auth.guard.ts
  libs/core/auth/src/lib/interfaces/jwt.interface.ts
  libs/core/auth/src/lib/strategy/jwt.strategy.ts
  libs/core/auth/tsconfig.json
  libs/core/auth/tsconfig.lib.json
  libs/core/auth/tsconfig.spec.json
  tsconfig.base.json
Labels: refactor

#44 feat(api-gateway): add rate-limit
  apps/api-gateway/src/app/app.module.ts
  apps/api-gateway/src/app/auth/auth.controller.ts
  package.json
  pnpm-lock.yaml
Labels: feat

#45 refactor: env get methods
  apps/api-gateway/src/app/auth/auth.controller.ts
  apps/api-gateway/src/app/auth/auth.module.ts
  apps/api-gateway/src/app/auth/auth.service.ts
  apps/api-gateway/src/app/docs-editor/docs-editor.controller.ts
  apps/api-gateway/src/app/docs-editor/docs-editor.module.ts
  apps/api-gateway/src/app/docs-editor/docs-editor.service.ts
  apps/api-gateway/src/app/projects/projects.controller.ts
  apps/api-gateway/src/app/projects/projects.module.ts
  apps/api-gateway/src/app/projects/projects.service.ts
  apps/api-gateway/src/app/users/users.controller.ts
  apps/api-gateway/src/app/users/users.module.ts
  apps/api-gateway/src/app/users/users.service.ts
Labels: refactor

#48 refactor: update prettier settings and code formated and add git hooks
  .prettierignore
  .prettierrc
  apps/api-gateway/src/app/auth/auth.controller.ts
  apps/api-gateway/src/app/auth/auth.service.ts
  apps/api-gateway/src/app/docs-editor/docs-editor.controller.ts
  apps/api-gateway/src/app/docs-editor/docs-editor.service.ts
  apps/api-gateway/src/app/projects/projects.controller.ts
  apps/api-gateway/src/app/projects/projects.service.ts
  apps/api-gateway/src/app/users/users.controller.ts
  apps/api-gateway/src/app/users/users.service.ts
  apps/project-service/src/main.ts
  apps/project-service/src/project-service.controller.ts
  apps/project-service/src/project-service.module.ts
  apps/project-service/src/project-service.service.ts
  apps/user-service/src/main.ts
  apps/user-service/src/user-service.controller.ts
  apps/user-service/src/user-service.module.ts
  architecture/.vscode/settings.json
  docker/docker-compose.yml
  hooks/post-commit
  hooks/pre-commit
  install-hooks.sh
  libs/core/auth/src/lib/decorators/jwt-decode.decorator.ts
  libs/project/src/lib/dto/index.ts
  package.json
Labels: feat, chore, refactor, style

#47 ci: add integration pipeline
  .github/workflows/integration.yml
  package.json
Labels: feat, ci

#46 feat: add env library
  libs/core/env/README.md
  libs/core/env/eslint.config.mjs
  libs/core/env/jest.config.ts
  libs/core/env/project.json
  libs/core/env/src/index.ts
  libs/core/env/src/lib/env-errors/env-errors.ts
  libs/core/env/src/lib/env.module.ts
  libs/core/env/src/lib/env.service.ts
  libs/core/env/tsconfig.json
  libs/core/env/tsconfig.lib.json
  libs/core/env/tsconfig.spec.json
  tsconfig.base.json
Labels: feat

#49 feat: add docs editor service
  apps/docs-editor-service-e2e/eslint.config.mjs
  apps/docs-editor-service-e2e/jest.config.ts
  apps/docs-editor-service-e2e/project.json
  apps/docs-editor-service-e2e/src/docs-editor-service/docs-editor-service.spec.ts
  apps/docs-editor-service-e2e/src/support/global-setup.ts
  apps/docs-editor-service-e2e/src/support/global-teardown.ts
  apps/docs-editor-service-e2e/src/support/test-setup.ts
  apps/docs-editor-service-e2e/tsconfig.json
  apps/docs-editor-service-e2e/tsconfig.spec.json
  apps/docs-editor-service/eslint.config.mjs
  apps/docs-editor-service/jest.config.ts
  apps/docs-editor-service/project.json
  apps/docs-editor-service/src/app/app.controller.ts
  apps/docs-editor-service/src/app/app.module.ts
  apps/docs-editor-service/src/app/app.service.ts
  apps/docs-editor-service/src/app/schemas/documentation.schema.ts
  apps/docs-editor-service/src/assets/.gitkeep
  apps/docs-editor-service/src/main.ts
  apps/docs-editor-service/tsconfig.app.json
  apps/docs-editor-service/tsconfig.json
  apps/docs-editor-service/tsconfig.spec.json
  apps/docs-editor-service/webpack.config.js
  nx.json
Labels: feat

#54 refactor(auth-lib): add auth lib service with method createAccessToken
  apps/api-gateway/src/app/auth/auth.module.ts
  apps/api-gateway/src/app/auth/auth.service.ts
  libs/core/auth/src/index.ts
  libs/core/auth/src/lib/auth-lib.module.ts
  libs/core/auth/src/lib/auth-lib.service.ts
  libs/core/auth/src/lib/auth.module.ts
  libs/core/auth/src/lib/interfaces/jwt.interface.ts
  libs/core/env/src/lib/env.module.ts
Labels: refactor

#57 refactor(DTO): add constructor in DTO
  libs/core/dtos/src/index.ts
  libs/core/dtos/src/lib/document-service-dtos/dtos/document-get.dto.ts
  libs/core/dtos/src/lib/interfaces/document-get.interface.ts
  libs/core/dtos/src/lib/interfaces/project-get.interface.ts
  libs/core/dtos/src/lib/interfaces/user-get.interface.ts
  libs/core/dtos/src/lib/project-service-dtos/dtos/project-get.dto.ts
  libs/core/dtos/src/lib/user-service-dtos/dtos/user-get.dto.ts
Labels: refactor

#53 refactor: api-gateway routes
  .env.example
  apps/api-gateway-e2e/eslint.config.mjs
  apps/api-gateway-e2e/jest.config.ts
  apps/api-gateway-e2e/project.json
  apps/api-gateway-e2e/src/api-gateway/api-gateway.spec.ts
  apps/api-gateway-e2e/src/support/global-setup.ts
  apps/api-gateway-e2e/src/support/global-teardown.ts
  apps/api-gateway-e2e/src/support/test-setup.ts
  apps/api-gateway-e2e/tsconfig.json
  apps/api-gateway-e2e/tsconfig.spec.json
  apps/api-gateway/jest.config.ts
  apps/api-gateway/src/app/app.module.ts
  apps/api-gateway/src/app/auth/auth.controller.ts
  apps/api-gateway/src/app/auth/auth.module.ts
  apps/api-gateway/src/app/auth/auth.service.ts
  apps/api-gateway/src/app/docs-editor/docs-editor.controller.ts
  apps/api-gateway/src/app/docs-editor/docs-editor.service.ts
  apps/api-gateway/src/app/document-editor/document-editor.controller.ts
  apps/api-gateway/src/app/document-editor/document-editor.module.ts
  apps/api-gateway/src/app/document-editor/document-editor.service.ts
  apps/api-gateway/src/app/project/projects.controller.ts
  apps/api-gateway/src/app/project/projects.module.ts
  apps/api-gateway/src/app/project/projects.service.ts
  apps/api-gateway/src/app/user/user.controller.ts
  apps/api-gateway/src/app/user/user.module.ts
  apps/api-gateway/src/app/user/user.service.ts
  apps/api-gateway/src/app/users/users.controller.ts
  apps/api-gateway/src/main.ts
  libs/core/auth/src/lib/auth-lib.service.ts
  libs/core/auth/src/lib/decorators/jwt-decode.decorator.ts
  libs/core/auth/src/lib/strategy/jwt.strategy.ts
  package.json
  pnpm-lock.yaml
Labels: refactor

#56 fix: user-service-inputs & userCreate-logs
  apps/user-service/src/schemas/user.schema.ts
  apps/user-service/src/user-service.controller.ts
  apps/user-service/src/user-service.service.ts
Labels: fix

#58 refactor: remove e2e modules
  apps/docs-editor-service-e2e/eslint.config.mjs
  apps/docs-editor-service-e2e/jest.config.ts
  apps/docs-editor-service-e2e/project.json
  apps/docs-editor-service-e2e/src/docs-editor-service/docs-editor-service.spec.ts
  apps/docs-editor-service-e2e/src/support/global-setup.ts
  apps/docs-editor-service-e2e/src/support/global-teardown.ts
  apps/docs-editor-service-e2e/src/support/test-setup.ts
  apps/docs-editor-service-e2e/tsconfig.json
  apps/docs-editor-service-e2e/tsconfig.spec.json
  apps/project-service-e2e/eslint.config.mjs
  apps/project-service-e2e/jest.config.ts
  apps/project-service-e2e/project.json
  apps/project-service-e2e/src/project-service/project-service.spec.ts
  apps/project-service-e2e/src/support/global-setup.ts
  apps/project-service-e2e/src/support/global-teardown.ts
  apps/project-service-e2e/src/support/test-setup.ts
  apps/project-service-e2e/tsconfig.json
  apps/project-service-e2e/tsconfig.spec.json
  apps/user-service-e2e/eslint.config.mjs
  apps/user-service-e2e/jest.config.ts
  apps/user-service-e2e/project.json
  apps/user-service-e2e/src/support/global-setup.ts
  apps/user-service-e2e/src/support/global-teardown.ts
  apps/user-service-e2e/src/support/test-setup.ts
  apps/user-service-e2e/src/user-service/user-service.spec.ts
  apps/user-service-e2e/tsconfig.json
  apps/user-service-e2e/tsconfig.spec.json
Labels: refactor

#59 refactor: project service inputs
  apps/project-service/src/main.ts
  apps/project-service/src/project-service.controller.ts
  apps/project-service/src/project-service.service.ts
  apps/project-service/src/schemas/project.schema.ts
Labels: refactor

#69 refactor: api-gateway-document-editor
  apps/api-gateway/src/app/document-editor/document-editor.controller.ts
  apps/api-gateway/src/app/document-editor/document-editor.service.ts
Labels: refactor

#72 refactor: document-project-user services
  apps/api-gateway/src/app/project/projects.controller.ts
  apps/api-gateway/src/app/user/user.controller.ts
  apps/document-editor/src/app/document-editor.controller.ts
  apps/document-editor/src/document-editor.controller.ts
  apps/document-editor/src/document-editor.module.ts
  apps/document-editor/src/document-editor.service.ts
  apps/document-editor/src/main.ts
  apps/document-editor/src/schemas/documentation.schema.ts
  apps/project-service/src/project-service.controller.ts
  apps/project-service/src/project-service.service.ts
  apps/user-service/src/user-service.controller.ts
  apps/user-service/src/user-service.service.ts
Labels: refactor

#74 refactor: deleteUser -> removeUser
  apps/user-service/src/user-service.service.ts
Labels: refactor

#63 docs: add contribute description in README.md
  README.md
Labels: feat, docs

#62 docs: add CODE_OF_CONDUCT.md file
  CODE_OF_CONDUCT.md
Labels: feat, docs

#61 docs: add CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: feat, docs

#78 docs: add new logo
  README.md
  assets/logo.svg
  docs/.gitkeep
  docs/images/DocuTide-logo.png
Labels: docs

#79 feat: add husky
  .husky/post-commit
  .husky/pre-commit
  hooks/post-commit
  install-hooks.sh
  package.json
  pnpm-lock.yaml
Labels: feat

#80 refactor: remove jest and jest configs
  jest.config.ts
  jest.preset.js
  libs/core/auth/jest.config.ts
  libs/core/env/jest.config.ts
  package.json
  pnpm-lock.yaml
Labels: refactor

#81 ci: add linting in integration pipeline
  .github/workflows/integration.yml
  .husky/pre-commit
  apps/client/shell/src/app/app.routes.ts
  apps/server/api-gateway/src/app/auth/auth.service.ts
  apps/server/document-editor/src/document-editor.controller.ts
  apps/server/project-service/src/project-service.controller.ts
  apps/server/user-service/src/user-service.controller.ts
  apps/server/user-service/src/user-service.service.ts
  eslint.config.mjs
  libs/core/auth/src/lib/auth-lib.module.ts
  libs/core/auth/src/lib/auth-lib.service.ts
  libs/core/auth/src/lib/decorators/jwt-decode.decorator.ts
  libs/core/dtos/src/lib/dtos.module.ts
  libs/core/env/src/lib/env.module.ts
  libs/core/env/src/lib/env.service.ts
  nx.json
  package.json
  pnpm-lock.yaml
Labels: fix, ci, refactor

#86 feat: add library with core schemas
  libs/core/schemas/README.md
  libs/core/schemas/project.json
  libs/core/schemas/src/index.ts
  libs/core/schemas/src/lib/migrations/migration_lock.toml
  libs/core/schemas/src/lib/prisma.service.ts
  libs/core/schemas/src/lib/prisma/schema.prisma
  libs/core/schemas/src/lib/prisma/schema/user.prisma
  libs/core/schemas/src/lib/schemas.module.ts
  libs/core/schemas/tsconfig.json
  libs/core/schemas/tsconfig.lib.json
  package.json
  pnpm-lock.yaml
  tsconfig.base.json
Labels: feat
