Repository neojelll/DocuTide, pull requests merged in 2025-03, with the labels that each got.

#89 hotfix: eslint config
  eslint.config.mjs
Labels: fix

#92 fix: library structure and cycle imports
  apps/server/api-gateway/src/app/document-editor/document-editor.controller.ts
  apps/server/api-gateway/src/app/document-editor/document-editor.service.ts
  apps/server/api-gateway/src/app/project/projects.controller.ts
  apps/server/api-gateway/src/app/project/projects.service.ts
  apps/server/api-gateway/src/app/user/user.controller.ts
  apps/server/api-gateway/src/app/user/user.service.ts
  apps/server/document-editor/src/document-editor.controller.ts
  apps/server/project-service/src/project-service.controller.ts
  apps/server/user-service/src/user-service.controller.ts
  libs/auth/auth-lib.module.ts
  libs/auth/auth-lib.service.ts
  libs/auth/decorators/jwt-decode.decorator.ts
  libs/auth/eslint.config.mjs
  libs/auth/guards/jwt-auth.guard.ts
  libs/auth/index.ts
  libs/auth/project.json
  libs/auth/src/index.ts
  libs/auth/strategy/jwt.strategy.ts
  libs/auth/tsconfig.json
  libs/auth/tsconfig.lib.json
  libs/client/.gitkeep
  libs/core/dto/auth/dto/user-sign-in.dto.ts
  libs/core/dto/auth/dto/user-sign-up.dto.ts
  libs/core/dto/document-service/dto/document-create.dto.ts
  libs/core/dto/document-service/dto/document-get.dto.ts
  libs/core/dto/document-service/dto/document-update.dto.ts
  libs/core/dto/document-service/validation-dto/document-create-validation.dto.ts
  libs/core/dto/document-service/validation-dto/document-update-validation.dto.ts
  libs/core/dto/index.ts
  libs/core/dto/project-service/dto/project-create.dto.ts
  libs/core/dto/project-service/dto/project-get.dto.ts
  libs/core/dto/project-service/dto/project-update.dto.ts
  libs/core/dto/project-service/validation-dto/project-create-validation.dto.ts
  libs/core/dto/project-service/validation-dto/project-update-validation.dto.ts
  libs/core/dto/user-service/dto/user-get.dto.ts
  libs/core/dto/user-service/dto/user-update.dto.ts
  libs/core/dto/user-service/validation-dto/user-update-validation.dto.ts
  libs/core/index.ts
  libs/core/interfaces/dto/document-get.interface.ts
  libs/core/interfaces/dto/project-get.interface.ts
  libs/core/interfaces/dto/user-get.interface.ts
  libs/core/interfaces/index.ts
  libs/core/interfaces/jwt/jwt.interface.ts
  libs/core/project.json
  libs/core/schemas/index.ts
  libs/core/schemas/migrations/migration_lock.toml
  libs/core/schemas/prisma/prisma.service.ts
  libs/core/schemas/prisma/schema.prisma
  libs/core/schemas/prisma/schema/user.prisma
  libs/core/schemas/prisma/schemas.module.ts
  libs/core/src/index.ts
  libs/core/tsconfig.lib.json
  libs/schemas/README.md
  libs/schemas/project.json
  libs/schemas/src/index.ts
  libs/schemas/tsconfig.json
  libs/schemas/tsconfig.lib.json
  tsconfig.base.json
Labels: fix, refactor

#93 hotfix: module federation settings
  apps/client/shell/eslint.config.mjs
  apps/client/shell/module-federation.config.ts
  apps/client/shell/vite.config.mts
  apps/client/shell/webpack.config.ts
  apps/client/shell/webpack.prod.config.ts
Labels: fix

#94 feat: add custom errors in core library
  libs/core/errors/custom.error.ts
  libs/core/errors/database.errors.ts
  libs/core/errors/index.ts
  libs/core/errors/mail.erros.ts
  libs/core/index.ts
  libs/core/interfaces/errors/custom-error.interface.ts
  libs/core/interfaces/index.ts
Labels: feat

#96 fix: add default values to emailConfirmed & notificationsEnabled
  libs/core/schemas/prisma/schema/user.prisma
Labels: fix

#97 fix: prisma scripts
  package.json
Labels: fix

#100 feat: add enums directory in core library
  libs/core/enums/index.ts
  libs/core/enums/user-identifier.type.ts
  libs/core/index.ts
Labels: feat

#98 feat: add repositories directory in core library
  libs/core/index.ts
  libs/core/repositories/index.ts
  libs/core/repositories/repositories.module.ts
  libs/core/repositories/user.repository.ts
Labels: feat

#106 fix: pre commit hook
  .husky/pre-commit
Labels: fix, perf

#102 refactor: diagrams to structurizr
  .github/workflows/update-diagrams.yml
  architecture/.vscode/settings.json
  architecture/architecture/__init__.py
  architecture/architecture/containers-diagram.py
  architecture/architecture/docs-editor-relationships-diagram.py
  architecture/architecture/messagebroker-relationships-diagram.py
  architecture/architecture/mvp-diagram.py
  architecture/architecture/system-context-diagram.py
  architecture/diagrams/containers-diagram.png
  architecture/diagrams/docs-editor-relationships-diagram.png
  architecture/diagrams/messagebroker-relationships-diagram.png
  architecture/diagrams/mvp-diagram.png
  architecture/diagrams/system-context-diagram.png
  architecture/poetry.lock
  architecture/pyproject.toml
  architecture/structurizr/workspace.dsl
  docker/architecture/Dockerfile
Labels: ci, refactor

#108 feat(nx-cloud): set up nx workspace
  nx.json
Labels: feat

#109 refactor: add tsconfigPaths() plugin in vitest.config
  package.json
  pnpm-lock.yaml
  vitest.config.mts
Labels: refactor

#110 fix(ci): add docker buildx action
  .github/workflows/update-diagrams.yml
Labels: fix, ci

#111 feat: add mongo support in prisma
  libs/core/schemas/index.ts
  libs/core/schemas/prisma/mongo/prisma-mongo.service.ts
  libs/core/schemas/prisma/mongo/schema.prisma
  libs/core/schemas/prisma/mongo/schema/document.prisma
  libs/core/schemas/prisma/postgres/migrations/migration_lock.toml
  libs/core/schemas/prisma/postgres/prisma-postgres.service.ts
  libs/core/schemas/prisma/postgres/schema.prisma
  libs/core/schemas/prisma/postgres/schema/user.prisma
  libs/core/schemas/prisma/prisma.service.ts
  libs/core/schemas/prisma/schema.prisma
  libs/core/schemas/prisma/schemas.module.ts
  package.json
Labels: feat
